require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7 # keep in sync with .circleci/config.yml and gemspec
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'fluent-plugin-kubernetes_metadata_filter.gemspec'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'fluent-plugin-kubernetes_metadata_filter.gemspec'
    - 'test/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'

Minitest/MultipleAssertions:
  Max: 5

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SpecialGlobalVars:
  EnforcedStyle: use_builtin_english_names

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
