version: 2.1

install: &install
  name: Install bundle
  command: |
            gem install bundler -v 2.4.22
            bundle config set --local path vendor/bundle
            bundle install

missingdeps: &missingdeps
  name: Install missing dependecies
  command: |
            cat /etc/os-release
            sed -e 's/^# deb-src/deb-src/g' /etc/apt/sources.list > /tmp/sources.list
            sudo cp /tmp/sources.list /etc/apt/sources.list
            sudo apt-get --allow-releaseinfo-change update
            sudo apt-get install cmake libicu-dev libssl-dev

test: &test
  name: Test bundle
  command: bundle exec rake test --trace

executors:
  ruby-2-7:
    docker:
      - image: cimg/ruby:2.7.8
jobs:
  "ruby-test":
    parameters:
      ruby-version:
        type: executor
    executor: << parameters.ruby-version >>
    working_directory: ~/fluent-plugin-kubernetes_metadata_filter
    steps:
      - run: *missingdeps
      - checkout
      - run: *install
      - run: *test
      - store_test_results:
            path: coverage
      - store_artifacts:
            path: coverage

workflows:
  "test_multiple_ruby_versions":
    jobs:
      - ruby-test:
          ruby-version: ruby-2-7
